name: example
description: "A demo for glass_animated_button package."
publish_to: 'none' # Prevents publishing this demo to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # 👇 Add this to connect with your main package
  glass_animated_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
