name: example
description: "A demo for glass_animated_button package."
publish_to: 'none' # Prevents publishing this demo to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 👇 Add this to connect with your main package
  glass_animated_button:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
