name: glass_animated_button
description: A customizable animated glassmorphic button for Flutter.
version: 1.0.8

homepage: https://github.com/Mujeebkhan-it/Flutter-package/tree/main/glass_animated_button
repository: https://github.com/Mujeebkhan-it/Flutter-package
issue_tracker: https://github.com/Mujeebkhan-it/Flutter-package/issues

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
